version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    image: "bonobo_board:latest"
    volumes:
      - ./apps:/bonobo-board/apps
      - ./modules:/bonobo-board/modules
    networks:
      - db_network
      - web_network
    environment:
      - SERVER=178.254.32.96
      - DOMAIN=bonoboboard.de
      - DEBUG=False
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/:ro
      - ./nginx/certs:/etc/nginx/ssl/:ro
      - ./nginx/www:/var/www/certbot/:ro
    networks:
      - web_network
    depends_on:
      - appseed-app
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/www:/var/www/certbot/:rw
      - ./nginx/certs:/etc/letsencrypt/:rw
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
