version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    image: "bonobo_board:latest"
    volumes:
      - ./apps:/bonobo-board/apps:rw
      - ./modules:/bonobo-board/modules:rw
    networks:
      - db_network
      - web_network
    environment:
      - DEBUG=True
      - SERVER=localhost
      - SECRET_KEY=S3cr3t_K#Key
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/appseed-app.conf
        target: /etc/nginx/conf.d/appseed-app.conf
    networks:
      - web_network
    depends_on:
      - appseed-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
