name: "On main push documentation build"
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "sphinx_src/"
        
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: sphinx_doc/_build
