name: "On main push documentation build"
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
      
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "cd ./sphinx_src && make html"
        docs-folder: "sphinx_src/"
        
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: sphinx_doc/html
        
    - name: deploy GH-page
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./sphinx_doc/html
