name: Continuous Integration
on: [push]

jobs:
  backend:
    name: CI-Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

     - name: Install dependencies
       working-directory: ./django-datta-able-1.0.4/apps/dhbw
       run: pip install -r requirements.txt

     - name: Run tests
       working-directory: ./django-datta-able-1.0.4/apps/dhbw/tests
       run: python test_suite